import {StyleSheet} from 'react-native';
import {fonts} from './fonts.style.asset';
import colors from './colors.style.asset';

export const typographies = StyleSheet.create({
  displayLarge: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 57,
    lineHeight: 64,
    color: colors.pureWhite,
    letterSpacing: 0.25,
    textAlign: 'left',
  },
  displayMedium: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 45,
    lineHeight: 53,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  displaySmall: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 36,
    lineHeight: 44,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  headingLarge: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 32,
    lineHeight: 40,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  headingMedium: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 28,
    lineHeight: 36,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  headingSmall: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 24,
    lineHeight: 32,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  titleLarge: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 22,
    lineHeight: 28,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  titleMedium: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 16,
    lineHeight: 24,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  titleSmall: {
    fontFamily: fonts.sourceSans3700,
    fontSize: 14,
    lineHeight: 20,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  labelLarge: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.1,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  labelMedium: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 12,
    lineHeight: 16,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  labelSmall: {
    fontFamily: fonts.sourceSans3600,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.5,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  bodyLarge: {
    fontFamily: fonts.sourceSans3400,
    fontSize: 16,
    lineHeight: 24,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  bodyMedium: {
    fontFamily: fonts.sourceSans3400,
    fontSize: 14,
    lineHeight: 20,
    color: colors.pureWhite,
    textAlign: 'left',
  },
  bodySmall: {
    fontFamily: fonts.sourceSans3400,
    fontSize: 12,
    lineHeight: 16,
    color: colors.pureWhite,
    textAlign: 'left',
  },
});
