const mobileNumberConstant = {
  AF: {
    icon: '🇦🇫',
    countryCode: 'AF',
    countryName: 'Afghanistan',
    callingCode: '93',
  },
  AL: {
    icon: '🇦🇱',
    countryCode: 'AL',
    countryName: 'Albania',
    callingCode: '355',
  },
  DZ: {
    icon: '🇩🇿',
    countryCode: 'DZ',
    countryName: 'Algeria',
    callingCode: '213',
  },
  AS: {
    icon: '🇦🇸',
    countryCode: 'AS',
    countryName: 'American Samoa',
    callingCode: '1684',
  },
  AD: {
    icon: '🇦🇩',
    countryCode: 'AD',
    countryName: 'Andorra',
    callingCode: '376',
  },
  AO: {
    icon: '🇦🇴',
    countryCode: 'AO',
    countryName: 'Angola',
    callingCode: '244',
  },
  AI: {
    icon: '🇦🇮',
    countryCode: 'AI',
    countryName: 'Anguilla',
    callingCode: '1264',
  },
  AG: {
    icon: '🇦🇬',
    countryCode: 'AG',
    countryName: 'Antigua and Barbuda',
    callingCode: '1268',
  },
  AR: {
    icon: '🇦🇷',
    countryCode: 'AR',
    countryName: 'Argentina',
    callingCode: '54',
  },
  AM: {
    icon: '🇦🇲',
    countryCode: 'AM',
    countryName: 'Armenia',
    callingCode: '374',
  },
  AW: {icon: '🇦🇼', countryCode: 'AW', countryName: 'Aruba', callingCode: '297'},
  AU: {
    icon: '🇦🇺',
    countryCode: 'AU',
    countryName: 'Australia',
    callingCode: '61',
  },
  AT: {
    icon: '🇦🇹',
    countryCode: 'AT',
    countryName: 'Austria',
    callingCode: '43',
  },
  AZ: {
    icon: '🇦🇿',
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    callingCode: '994',
  },
  BS: {
    icon: '🇧🇸',
    countryCode: 'BS',
    countryName: 'Bahamas',
    callingCode: '1242',
  },
  BH: {
    icon: '🇧🇭',
    countryCode: 'BH',
    countryName: 'Bahrain',
    callingCode: '973',
  },
  BD: {
    icon: '🇧🇩',
    countryCode: 'BD',
    countryName: 'Bangladesh',
    callingCode: '880',
  },
  BB: {
    icon: '🇧🇧',
    countryCode: 'BB',
    countryName: 'Barbados',
    callingCode: '1246',
  },
  BY: {
    icon: '🇧🇾',
    countryCode: 'BY',
    countryName: 'Belarus',
    callingCode: '375',
  },
  BE: {
    icon: '🇧🇪',
    countryCode: 'BE',
    countryName: 'Belgium',
    callingCode: '32',
  },
  BZ: {
    icon: '🇧🇿',
    countryCode: 'BZ',
    countryName: 'Belize',
    callingCode: '501',
  },
  BJ: {icon: '🇧🇯', countryCode: 'BJ', countryName: 'Benin', callingCode: '229'},
  BM: {
    icon: '🇧🇲',
    countryCode: 'BM',
    countryName: 'Bermuda',
    callingCode: '1441',
  },
  BT: {
    icon: '🇧🇹',
    countryCode: 'BT',
    countryName: 'Bhutan',
    callingCode: '975',
  },
  BO: {
    icon: '🇧🇴',
    countryCode: 'BO',
    countryName: 'Bolivia',
    callingCode: '591',
  },
  BA: {
    icon: '🇧🇦',
    countryCode: 'BA',
    countryName: 'Bosnia and Herzegovina',
    callingCode: '387',
  },
  BW: {
    icon: '🇧🇼',
    countryCode: 'BW',
    countryName: 'Botswana',
    callingCode: '267',
  },
  BR: {icon: '🇧🇷', countryCode: 'BR', countryName: 'Brazil', callingCode: '55'},
  IO: {
    icon: '🇮🇴',
    countryCode: 'IO',
    countryName: 'British Indian Ocean Territory',
    callingCode: '246',
  },
  VG: {
    icon: '🇻🇬',
    countryCode: 'VG',
    countryName: 'British Virgin Islands',
    callingCode: '1284',
  },
  BN: {
    icon: '🇧🇳',
    countryCode: 'BN',
    countryName: 'Brunei',
    callingCode: '673',
  },
  BG: {
    icon: '🇧🇬',
    countryCode: 'BG',
    countryName: 'Bulgaria',
    callingCode: '359',
  },
  BF: {
    icon: '🇧🇫',
    countryCode: 'BF',
    countryName: 'Burkina Faso',
    callingCode: '226',
  },
  BI: {
    icon: '🇧🇮',
    countryCode: 'BI',
    countryName: 'Burundi',
    callingCode: '257',
  },
  KH: {
    icon: '🇰🇭',
    countryCode: 'KH',
    countryName: 'Cambodia',
    callingCode: '855',
  },
  CM: {
    icon: '🇨🇲',
    countryCode: 'CM',
    countryName: 'Cameroon',
    callingCode: '237',
  },
  CA: {icon: '🇨🇦', countryCode: 'CA', countryName: 'Canada', callingCode: '1'},
  CV: {
    icon: '🇨🇻',
    countryCode: 'CV',
    countryName: 'Cape Verde',
    callingCode: '238',
  },
  KY: {
    icon: '🇰🇾',
    countryCode: 'KY',
    countryName: 'Cayman Islands',
    callingCode: '1345',
  },
  CF: {
    icon: '🇨🇫',
    countryCode: 'CF',
    countryName: 'Central African Republic',
    callingCode: '236',
  },
  TD: {icon: '🇹🇩', countryCode: 'TD', countryName: 'Chad', callingCode: '235'},
  CL: {icon: '🇨🇱', countryCode: 'CL', countryName: 'Chile', callingCode: '56'},
  CN: {icon: '🇨🇳', countryCode: 'CN', countryName: 'China', callingCode: '86'},
  CO: {
    icon: '🇨🇴',
    countryCode: 'CO',
    countryName: 'Colombia',
    callingCode: '57',
  },
  KM: {
    icon: '🇰🇲',
    countryCode: 'KM',
    countryName: 'Comoros',
    callingCode: '269',
  },
  CG: {
    icon: '🇨🇬',
    countryCode: 'CG',
    countryName: 'Congo (Congo-Brazzaville)',
    callingCode: '242',
  },
  CD: {
    icon: '🇨🇩',
    countryCode: 'CD',
    countryName: 'Congo (Congo-Kinshasa)',
    callingCode: '243',
  },
  CK: {
    icon: '🇨🇰',
    countryCode: 'CK',
    countryName: 'Cook Islands',
    callingCode: '682',
  },
  CR: {
    icon: '🇨🇷',
    countryCode: 'CR',
    countryName: 'Costa Rica',
    callingCode: '506',
  },
  HR: {
    icon: '🇭🇷',
    countryCode: 'HR',
    countryName: 'Croatia',
    callingCode: '385',
  },
  CU: {icon: '🇨🇺', countryCode: 'CU', countryName: 'Cuba', callingCode: '53'},
  CY: {
    icon: '🇨🇾',
    countryCode: 'CY',
    countryName: 'Cyprus',
    callingCode: '357',
  },
  CZ: {
    icon: '🇨🇿',
    countryCode: 'CZ',
    countryName: 'Czech Republic',
    callingCode: '420',
  },
  DK: {
    icon: '🇩🇰',
    countryCode: 'DK',
    countryName: 'Denmark',
    callingCode: '45',
  },
  DJ: {
    icon: '🇩🇯',
    countryCode: 'DJ',
    countryName: 'Djibouti',
    callingCode: '253',
  },
  DM: {
    icon: '🇩🇲',
    countryCode: 'DM',
    countryName: 'Dominica',
    callingCode: '1767',
  },
  DO: {
    icon: '🇩🇴',
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    callingCode: '1809',
  },
  EC: {
    icon: '🇪🇨',
    countryCode: 'EC',
    countryName: 'Ecuador',
    callingCode: '593',
  },
  EG: {icon: '🇪🇬', countryCode: 'EG', countryName: 'Egypt', callingCode: '20'},
  SV: {
    icon: '🇸🇻',
    countryCode: 'SV',
    countryName: 'El Salvador',
    callingCode: '503',
  },
  GQ: {
    icon: '🇬🇶',
    countryCode: 'GQ',
    countryName: 'Equatorial Guinea',
    callingCode: '240',
  },
  ER: {
    icon: '🇪🇷',
    countryCode: 'ER',
    countryName: 'Eritrea',
    callingCode: '291',
  },
  EE: {
    icon: '🇪🇪',
    countryCode: 'EE',
    countryName: 'Estonia',
    callingCode: '372',
  },
  SZ: {
    icon: '🇸🇿',
    countryCode: 'SZ',
    countryName: 'Eswatini',
    callingCode: '268',
  },
  ET: {
    icon: '🇪🇹',
    countryCode: 'ET',
    countryName: 'Ethiopia',
    callingCode: '251',
  },
  FJ: {icon: '🇫🇯', countryCode: 'FJ', countryName: 'Fiji', callingCode: '679'},
  FI: {
    icon: '🇫🇮',
    countryCode: 'FI',
    countryName: 'Finland',
    callingCode: '358',
  },
  FR: {icon: '🇫🇷', countryCode: 'FR', countryName: 'France', callingCode: '33'},
  GF: {
    icon: '🇬🇫',
    countryCode: 'GF',
    countryName: 'French Guiana',
    callingCode: '594',
  },
  PF: {
    icon: '🇵🇫',
    countryCode: 'PF',
    countryName: 'French Polynesia',
    callingCode: '689',
  },
  GA: {icon: '🇬🇦', countryCode: 'GA', countryName: 'Gabon', callingCode: '241'},
  GM: {
    icon: '🇬🇲',
    countryCode: 'GM',
    countryName: 'Gambia',
    callingCode: '220',
  },
  GE: {
    icon: '🇬🇪',
    countryCode: 'GE',
    countryName: 'Georgia',
    callingCode: '995',
  },
  DE: {
    icon: '🇩🇪',
    countryCode: 'DE',
    countryName: 'Germany',
    callingCode: '49',
  },
  GH: {icon: '🇬🇭', countryCode: 'GH', countryName: 'Ghana', callingCode: '233'},
  GI: {
    icon: '🇬🇮',
    countryCode: 'GI',
    countryName: 'Gibraltar',
    callingCode: '350',
  },
  GR: {icon: '🇬🇷', countryCode: 'GR', countryName: 'Greece', callingCode: '30'},
  GL: {
    icon: '🇬🇱',
    countryCode: 'GL',
    countryName: 'Greenland',
    callingCode: '299',
  },
  GD: {
    icon: '🇬🇩',
    countryCode: 'GD',
    countryName: 'Grenada',
    callingCode: '1473',
  },
  GP: {
    icon: '🇬🇵',
    countryCode: 'GP',
    countryName: 'Guadeloupe',
    callingCode: '590',
  },
  GU: {
    icon: '🇬🇺',
    countryCode: 'GU',
    countryName: 'Guam',
    callingCode: '1671',
  },
  GT: {
    icon: '🇬🇹',
    countryCode: 'GT',
    countryName: 'Guatemala',
    callingCode: '502',
  },
  GN: {
    icon: '🇬🇳',
    countryCode: 'GN',
    countryName: 'Guinea',
    callingCode: '224',
  },
  GW: {
    icon: '🇬🇼',
    countryCode: 'GW',
    countryName: 'Guinea-Bissau',
    callingCode: '245',
  },
  GY: {
    icon: '🇬🇾',
    countryCode: 'GY',
    countryName: 'Guyana',
    callingCode: '592',
  },
  HT: {icon: '🇭🇹', countryCode: 'HT', countryName: 'Haiti', callingCode: '509'},
  HN: {
    icon: '🇭🇳',
    countryCode: 'HN',
    countryName: 'Honduras',
    callingCode: '504',
  },
  HK: {
    icon: '🇭🇰',
    countryCode: 'HK',
    countryName: 'Hong Kong',
    callingCode: '852',
  },
  HU: {
    icon: '🇭🇺',
    countryCode: 'HU',
    countryName: 'Hungary',
    callingCode: '36',
  },
  IS: {
    icon: '🇮🇸',
    countryCode: 'IS',
    countryName: 'Iceland',
    callingCode: '354',
  },
  IN: {icon: '🇮🇳', countryCode: 'IN', countryName: 'India', callingCode: '91'},
  ID: {
    icon: '🇮🇩',
    countryCode: 'ID',
    countryName: 'Indonesia',
    callingCode: '62',
  },
  IR: {icon: '🇮🇷', countryCode: 'IR', countryName: 'Iran', callingCode: '98'},
  IQ: {icon: '🇮🇶', countryCode: 'IQ', countryName: 'Iraq', callingCode: '964'},
  IE: {
    icon: '🇮🇪',
    countryCode: 'IE',
    countryName: 'Ireland',
    callingCode: '353',
  },
  IL: {
    icon: '🇮🇱',
    countryCode: 'IL',
    countryName: 'Israel',
    callingCode: '972',
  },
  IT: {icon: '🇮🇹', countryCode: 'IT', countryName: 'Italy', callingCode: '39'},
  JM: {
    icon: '🇯🇲',
    countryCode: 'JM',
    countryName: 'Jamaica',
    callingCode: '1876',
  },
  JP: {icon: '🇯🇵', countryCode: 'JP', countryName: 'Japan', callingCode: '81'},
  JO: {
    icon: '🇯🇴',
    countryCode: 'JO',
    countryName: 'Jordan',
    callingCode: '962',
  },
  KZ: {
    icon: '🇰🇿',
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    callingCode: '7',
  },
  KE: {icon: '🇰🇪', countryCode: 'KE', countryName: 'Kenya', callingCode: '254'},
  KI: {
    icon: '🇰🇮',
    countryCode: 'KI',
    countryName: 'Kiribati',
    callingCode: '686',
  },
  KP: {
    icon: '🇰🇵',
    countryCode: 'KP',
    countryName: 'North Korea',
    callingCode: '850',
  },
  KR: {
    icon: '🇰🇷',
    countryCode: 'KR',
    countryName: 'South Korea',
    callingCode: '82',
  },
  KW: {
    icon: '🇰🇼',
    countryCode: 'KW',
    countryName: 'Kuwait',
    callingCode: '965',
  },
  KG: {
    icon: '🇰🇬',
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
    callingCode: '996',
  },
  LA: {icon: '🇱🇦', countryCode: 'LA', countryName: 'Laos', callingCode: '856'},
  LV: {
    icon: '🇱🇻',
    countryCode: 'LV',
    countryName: 'Latvia',
    callingCode: '371',
  },
  LB: {
    icon: '🇱🇧',
    countryCode: 'LB',
    countryName: 'Lebanon',
    callingCode: '961',
  },
  LS: {
    icon: '🇱🇸',
    countryCode: 'LS',
    countryName: 'Lesotho',
    callingCode: '266',
  },
  LR: {
    icon: '🇱🇷',
    countryCode: 'LR',
    countryName: 'Liberia',
    callingCode: '231',
  },
  LY: {icon: '🇱🇾', countryCode: 'LY', countryName: 'Libya', callingCode: '218'},
  LI: {
    icon: '🇱🇮',
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    callingCode: '423',
  },
  LT: {
    icon: '🇱🇹',
    countryCode: 'LT',
    countryName: 'Lithuania',
    callingCode: '370',
  },
  LU: {
    icon: '🇱🇺',
    countryCode: 'LU',
    countryName: 'Luxembourg',
    callingCode: '352',
  },
  MO: {icon: '🇲🇴', countryCode: 'MO', countryName: 'Macau', callingCode: '853'},
  MG: {
    icon: '🇲🇬',
    countryCode: 'MG',
    countryName: 'Madagascar',
    callingCode: '261',
  },
  MW: {
    icon: '🇲🇼',
    countryCode: 'MW',
    countryName: 'Malawi',
    callingCode: '265',
  },
  MY: {
    icon: '🇲🇾',
    countryCode: 'MY',
    countryName: 'Malaysia',
    callingCode: '60',
  },
  MV: {
    icon: '🇲🇻',
    countryCode: 'MV',
    countryName: 'Maldives',
    callingCode: '960',
  },
  ML: {icon: '🇲🇱', countryCode: 'ML', countryName: 'Mali', callingCode: '223'},
  MT: {icon: '🇲🇹', countryCode: 'MT', countryName: 'Malta', callingCode: '356'},
  MH: {
    icon: '🇲🇭',
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    callingCode: '692',
  },
  MQ: {
    icon: '🇲🇶',
    countryCode: 'MQ',
    countryName: 'Martinique',
    callingCode: '596',
  },
  MR: {
    icon: '🇲🇷',
    countryCode: 'MR',
    countryName: 'Mauritania',
    callingCode: '222',
  },
  MU: {
    icon: '🇲🇺',
    countryCode: 'MU',
    countryName: 'Mauritius',
    callingCode: '230',
  },
  YT: {
    icon: '🇾🇹',
    countryCode: 'YT',
    countryName: 'Mayotte',
    callingCode: '262',
  },
  MX: {icon: '🇲🇽', countryCode: 'MX', countryName: 'Mexico', callingCode: '52'},
  FM: {
    icon: '🇫🇲',
    countryCode: 'FM',
    countryName: 'Micronesia',
    callingCode: '691',
  },
  MD: {
    icon: '🇲🇩',
    countryCode: 'MD',
    countryName: 'Moldova',
    callingCode: '373',
  },
  MC: {
    icon: '🇲🇨',
    countryCode: 'MC',
    countryName: 'Monaco',
    callingCode: '377',
  },
  MN: {
    icon: '🇲🇳',
    countryCode: 'MN',
    countryName: 'Mongolia',
    callingCode: '976',
  },
  ME: {
    icon: '🇲🇪',
    countryCode: 'ME',
    countryName: 'Montenegro',
    callingCode: '382',
  },
  MS: {
    icon: '🇲🇸',
    countryCode: 'MS',
    countryName: 'Montserrat',
    callingCode: '1664',
  },
  MA: {
    icon: '🇲🇦',
    countryCode: 'MA',
    countryName: 'Morocco',
    callingCode: '212',
  },
  MZ: {
    icon: '🇲🇿',
    countryCode: 'MZ',
    countryName: 'Mozambique',
    callingCode: '258',
  },
  MM: {
    icon: '🇲🇲',
    countryCode: 'MM',
    countryName: 'Myanmar',
    callingCode: '95',
  },
  NA: {
    icon: '🇳🇦',
    countryCode: 'NA',
    countryName: 'Namibia',
    callingCode: '264',
  },
  NR: {icon: '🇳🇷', countryCode: 'NR', countryName: 'Nauru', callingCode: '674'},
  NP: {icon: '🇳🇵', countryCode: 'NP', countryName: 'Nepal', callingCode: '977'},
  NL: {
    icon: '🇳🇱',
    countryCode: 'NL',
    countryName: 'Netherlands',
    callingCode: '31',
  },
  NC: {
    icon: '🇳🇨',
    countryCode: 'NC',
    countryName: 'New Caledonia',
    callingCode: '687',
  },
  NZ: {
    icon: '🇳🇿',
    countryCode: 'NZ',
    countryName: 'New Zealand',
    callingCode: '64',
  },
  NI: {
    icon: '🇳🇮',
    countryCode: 'NI',
    countryName: 'Nicaragua',
    callingCode: '505',
  },
  NE: {icon: '🇳🇪', countryCode: 'NE', countryName: 'Niger', callingCode: '227'},
  NG: {
    icon: '🇳🇬',
    countryCode: 'NG',
    countryName: 'Nigeria',
    callingCode: '234',
  },
  NU: {icon: '🇳🇺', countryCode: 'NU', countryName: 'Niue', callingCode: '683'},
  NF: {
    icon: '🇳🇫',
    countryCode: 'NF',
    countryName: 'Norfolk Island',
    callingCode: '672',
  },
  MP: {
    icon: '🇲🇵',
    countryCode: 'MP',
    countryName: 'Northern Mariana Islands',
    callingCode: '1670',
  },
  NO: {icon: '🇳🇴', countryCode: 'NO', countryName: 'Norway', callingCode: '47'},
  OM: {icon: '🇴🇲', countryCode: 'OM', countryName: 'Oman', callingCode: '968'},
  PK: {
    icon: '🇵🇰',
    countryCode: 'PK',
    countryName: 'Pakistan',
    callingCode: '92',
  },
  PW: {icon: '🇵🇼', countryCode: 'PW', countryName: 'Palau', callingCode: '680'},
  PA: {
    icon: '🇵🇦',
    countryCode: 'PA',
    countryName: 'Panama',
    callingCode: '507',
  },
  PG: {
    icon: '🇵🇬',
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    callingCode: '675',
  },
  PY: {
    icon: '🇵🇾',
    countryCode: 'PY',
    countryName: 'Paraguay',
    callingCode: '595',
  },
  PE: {icon: '🇵🇪', countryCode: 'PE', countryName: 'Peru', callingCode: '51'},
  PH: {
    icon: '🇵🇭',
    countryCode: 'PH',
    countryName: 'Philippines',
    callingCode: '63',
  },
  PL: {icon: '🇵🇱', countryCode: 'PL', countryName: 'Poland', callingCode: '48'},
  PT: {
    icon: '🇵🇹',
    countryCode: 'PT',
    countryName: 'Portugal',
    callingCode: '351',
  },
  PR: {
    icon: '🇵🇷',
    countryCode: 'PR',
    countryName: 'Puerto Rico',
    callingCode: '1787',
  },
  QA: {icon: '🇶🇦', countryCode: 'QA', countryName: 'Qatar', callingCode: '974'},
  RE: {
    icon: '🇷🇪',
    countryCode: 'RE',
    countryName: 'Réunion',
    callingCode: '262',
  },
  RO: {
    icon: '🇷🇴',
    countryCode: 'RO',
    countryName: 'Romania',
    callingCode: '40',
  },
  RU: {icon: '🇷🇺', countryCode: 'RU', countryName: 'Russia', callingCode: '7'},
  RW: {
    icon: '🇷🇼',
    countryCode: 'RW',
    countryName: 'Rwanda',
    callingCode: '250',
  },
  BL: {
    icon: '🇧🇱',
    countryCode: 'BL',
    countryName: 'Saint Barthélemy',
    callingCode: '590',
  },
  SH: {
    icon: '🇸🇭',
    countryCode: 'SH',
    countryName: 'Saint Helena',
    callingCode: '290',
  },
  KN: {
    icon: '🇰🇳',
    countryCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    callingCode: '1869',
  },
  LC: {
    icon: '🇱🇨',
    countryCode: 'LC',
    countryName: 'Saint Lucia',
    callingCode: '1758',
  },
  MF: {
    icon: '🇲🇫',
    countryCode: 'MF',
    countryName: 'Saint Martin',
    callingCode: '590',
  },
  PM: {
    icon: '🇵🇲',
    countryCode: 'PM',
    countryName: 'Saint Pierre and Miquelon',
    callingCode: '508',
  },
  VC: {
    icon: '🇻🇨',
    countryCode: 'VC',
    countryName: 'Saint Vincent and the Grenadines',
    callingCode: '1784',
  },
  WS: {icon: '🇼🇸', countryCode: 'WS', countryName: 'Samoa', callingCode: '685'},
  SM: {
    icon: '🇸🇲',
    countryCode: 'SM',
    countryName: 'San Marino',
    callingCode: '378',
  },
  ST: {
    icon: '🇸🇹',
    countryCode: 'ST',
    countryName: 'São Tomé and Príncipe',
    callingCode: '239',
  },
  SA: {
    icon: '🇸🇦',
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    callingCode: '966',
  },
  SN: {
    icon: '🇸🇳',
    countryCode: 'SN',
    countryName: 'Senegal',
    callingCode: '221',
  },
  RS: {
    icon: '🇷🇸',
    countryCode: 'RS',
    countryName: 'Serbia',
    callingCode: '381',
  },
  SC: {
    icon: '🇸🇨',
    countryCode: 'SC',
    countryName: 'Seychelles',
    callingCode: '248',
  },
  SL: {
    icon: '🇸🇱',
    countryCode: 'SL',
    countryName: 'Sierra Leone',
    callingCode: '232',
  },
  SG: {
    icon: '🇸🇬',
    countryCode: 'SG',
    countryName: 'Singapore',
    callingCode: '65',
  },
  SX: {
    icon: '🇸🇽',
    countryCode: 'SX',
    countryName: 'Sint Maarten',
    callingCode: '1721',
  },
  SK: {
    icon: '🇸🇰',
    countryCode: 'SK',
    countryName: 'Slovakia',
    callingCode: '421',
  },
  SI: {
    icon: '🇸🇮',
    countryCode: 'SI',
    countryName: 'Slovenia',
    callingCode: '386',
  },
  SB: {
    icon: '🇸🇧',
    countryCode: 'SB',
    countryName: 'Solomon Islands',
    callingCode: '677',
  },
  SO: {
    icon: '🇸🇴',
    countryCode: 'SO',
    countryName: 'Somalia',
    callingCode: '252',
  },
  ZA: {
    icon: '🇿🇦',
    countryCode: 'ZA',
    countryName: 'South Africa',
    callingCode: '27',
  },
  GS: {
    icon: '🇬🇸',
    countryCode: 'GS',
    countryName: 'South Georgia and the South Sandwich Islands',
    callingCode: '500',
  },
  SS: {
    icon: '🇸🇸',
    countryCode: 'SS',
    countryName: 'South Sudan',
    callingCode: '211',
  },
  ES: {icon: '🇪🇸', countryCode: 'ES', countryName: 'Spain', callingCode: '34'},
  LK: {
    icon: '🇱🇰',
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    callingCode: '94',
  },
  SD: {icon: '🇸🇩', countryCode: 'SD', countryName: 'Sudan', callingCode: '249'},
  SR: {
    icon: '🇸🇷',
    countryCode: 'SR',
    countryName: 'Suriname',
    callingCode: '597',
  },
  SJ: {
    icon: '🇸🇯',
    countryCode: 'SJ',
    countryName: 'Svalbard and Jan Mayen',
    callingCode: '47',
  },
  SE: {icon: '🇸🇪', countryCode: 'SE', countryName: 'Sweden', callingCode: '46'},
  CH: {
    icon: '🇨🇭',
    countryCode: 'CH',
    countryName: 'Switzerland',
    callingCode: '41',
  },
  SY: {icon: '🇸🇾', countryCode: 'SY', countryName: 'Syria', callingCode: '963'},
  TW: {
    icon: '🇹🇼',
    countryCode: 'TW',
    countryName: 'Taiwan',
    callingCode: '886',
  },
  TJ: {
    icon: '🇹🇯',
    countryCode: 'TJ',
    countryName: 'Tajikistan',
    callingCode: '992',
  },
  TZ: {
    icon: '🇹🇿',
    countryCode: 'TZ',
    countryName: 'Tanzania',
    callingCode: '255',
  },
  TH: {
    icon: '🇹🇭',
    countryCode: 'TH',
    countryName: 'Thailand',
    callingCode: '66',
  },
  TL: {
    icon: '🇹🇱',
    countryCode: 'TL',
    countryName: 'Timor-Leste',
    callingCode: '670',
  },
  TG: {icon: '🇹🇬', countryCode: 'TG', countryName: 'Togo', callingCode: '228'},
  TK: {
    icon: '🇹🇰',
    countryCode: 'TK',
    countryName: 'Tokelau',
    callingCode: '690',
  },
  TO: {icon: '🇹🇴', countryCode: 'TO', countryName: 'Tonga', callingCode: '676'},
  TT: {
    icon: '🇹🇹',
    countryCode: 'TT',
    countryName: 'Trinidad and Tobago',
    callingCode: '1868',
  },
  TN: {
    icon: '🇹🇳',
    countryCode: 'TN',
    countryName: 'Tunisia',
    callingCode: '216',
  },
  TR: {icon: '🇹🇷', countryCode: 'TR', countryName: 'Turkey', callingCode: '90'},
  TM: {
    icon: '🇹🇲',
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    callingCode: '993',
  },
  TC: {
    icon: '🇹🇨',
    countryCode: 'TC',
    countryName: 'Turks and Caicos Islands',
    callingCode: '1649',
  },
  TV: {
    icon: '🇹🇻',
    countryCode: 'TV',
    countryName: 'Tuvalu',
    callingCode: '688',
  },
  UG: {
    icon: '🇺🇬',
    countryCode: 'UG',
    countryName: 'Uganda',
    callingCode: '256',
  },
  UA: {
    icon: '🇺🇦',
    countryCode: 'UA',
    countryName: 'Ukraine',
    callingCode: '380',
  },
  AE: {
    icon: '🇦🇪',
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    callingCode: '971',
  },
  GB: {
    icon: '🇬🇧',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    callingCode: '44',
  },
  US: {
    icon: '🇺🇸',
    countryCode: 'US',
    countryName: 'United States',
    callingCode: '1',
  },
  UY: {
    icon: '🇺🇾',
    countryCode: 'UY',
    countryName: 'Uruguay',
    callingCode: '598',
  },
  UZ: {
    icon: '🇺🇿',
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    callingCode: '998',
  },
  VU: {
    icon: '🇻🇺',
    countryCode: 'VU',
    countryName: 'Vanuatu',
    callingCode: '678',
  },
  VA: {
    icon: '🇻🇦',
    countryCode: 'VA',
    countryName: 'Vatican City',
    callingCode: '39',
  },
  VE: {
    icon: '🇻🇪',
    countryCode: 'VE',
    countryName: 'Venezuela',
    callingCode: '58',
  },
  VN: {
    icon: '🇻🇳',
    countryCode: 'VN',
    countryName: 'Vietnam',
    callingCode: '84',
  },
  WF: {
    icon: '🇼🇫',
    countryCode: 'WF',
    countryName: 'Wallis and Futuna',
    callingCode: '681',
  },
  EH: {
    icon: '🇪🇭',
    countryCode: 'EH',
    countryName: 'Western Sahara',
    callingCode: '212',
  },
  YE: {icon: '🇾🇪', countryCode: 'YE', countryName: 'Yemen', callingCode: '967'},
  ZM: {
    icon: '🇿🇲',
    countryCode: 'ZM',
    countryName: 'Zambia',
    callingCode: '260',
  },
  ZW: {
    icon: '🇿🇼',
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    callingCode: '263',
  },
};

export default mobileNumberConstant;
